device: "cuda"
logdir: "logs"
checkpoints: "checkpoints"
data:
  name: "RECOVERY" 
  img_root: "data/new_modified_data/RECOVERY/images"
  data_path: "data/new_modified_data/RECOVERY/recoveryn_modified.csv"
  txt_col: "body_text"
  img_col: "image"
  tar_col: "reliability"
  idx_col: "Unnamed: 0"
  batch_size: 16
  num_workers: 4
  max_len: 512
  chunk_len: 200
  overlap_len: 50
model:
  name: "LstmVgg"
  modality: "multi"
  vocab_size: 0
  embedding_dim: 100
  hidden_dim: 256
  num_layers: 2
  dropout: 0.2
  common_hidden_dim: 512
  output_dim: 1
training:
  scheme: 2 # 0: base, 1: only attention, 2: attention with regularization
  beta: 0.7 # high:low
  margin: 0.2
  epochs: 100
  lr: 0.0001
  warmup_steps: 0